quarkus:
  qute:
    strict-rendering: false
  http:
    port: 8080
  log:
    level: ERROR
    console:
      color: true
      format: '%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n'

bot:
  limit: 2
  symbol:
    limit: 1
    list:
      - BTCUSDT
      - ETHUSDT
      - XRPUSDT
  parameters: